matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
    - os: linux
      dist: xenial
      sudo: false
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      before_install:
        - brew update
        - brew list protobuf &>/dev/null || brew install protobuf
addons:
  apt:
    packages:
      - libprotobuf-dev
      - protobuf-compiler
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
language: ruby
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
script:
  - rake spec
